// src/api/apiService.jsx
//
// Transitional façade. The per-domain API modules are the new home for
// these functions. This file re-exports them so existing callers keep
// working until they are migrated; it will be deleted at the end of the
// frontend-module-cleanup migration.

import {
    getAccounts,
    getAccount,
    updateAccount,
    deleteAccount,
    getCharacter,
    updateCharacter,
    deleteCharacter,
    refreshCharacter,
    addCharacter,
    getAssociations,
    associateCharacter,
    unassociateCharacter,
} from './accountsApi';
import {
    getSkillPlans,
    getSkillPlan,
    createSkillPlan,
    copySkillPlan,
    deleteSkillPlan,
    saveSkillPlan,
} from './skillPlansApi';
import {
    saveUserSelections,
    syncSubdirectory,
    syncAllSubdirectories,
    chooseSettingsDir,
    chooseDefaultDirectory,
    backupDirectory,
    resetToDefaultDirectory,
} from './syncApi';
import {
    getConfig,
    updateConfig,
    checkEVEConfiguration,
    saveEVECredentials,
} from './configApi';
import {
    getEveSkillPlans,
    getEveProfiles,
    getEveConversions,
} from './esiApi';
import { getFuzzworksStatus, updateFuzzworks } from './fuzzworksApi';
import {
    logout,
    initiateLogin,
    finalizelogin,
    getSession,
    validateSession,
    refreshSession,
    getActiveSessions,
} from './authApi';

export {
    getAccounts,
    getAccount,
    updateAccount,
    deleteAccount,
    getCharacter,
    updateCharacter,
    deleteCharacter,
    refreshCharacter,
    addCharacter,
    getAssociations,
    associateCharacter,
    unassociateCharacter,
    getSkillPlans,
    getSkillPlan,
    createSkillPlan,
    copySkillPlan,
    deleteSkillPlan,
    saveSkillPlan,
    saveUserSelections,
    syncSubdirectory,
    syncAllSubdirectories,
    chooseSettingsDir,
    chooseDefaultDirectory,
    backupDirectory,
    resetToDefaultDirectory,
    getConfig,
    updateConfig,
    checkEVEConfiguration,
    saveEVECredentials,
    getEveSkillPlans,
    getEveProfiles,
    getEveConversions,
    getFuzzworksStatus,
    updateFuzzworks,
    logout,
    initiateLogin,
    finalizelogin,
    getSession,
    validateSession,
    refreshSession,
    getActiveSessions,
};

// Default export for legacy callers (stores etc.). Will be removed
// once the migration is complete.
export default {
    getAccounts,
    getAccount,
    updateAccount,
    deleteAccount,
    getCharacter,
    updateCharacter,
    deleteCharacter,
    refreshCharacter,
    addCharacter,
    getAssociations,
    associateCharacter,
    unassociateCharacter,
    getConfig,
    updateConfig,
    getSession,
    validateSession,
    refreshSession,
    getActiveSessions,
    checkEVEConfiguration,
    saveEVECredentials,
    getEveSkillPlans,
    getEveProfiles,
    getEveConversions,
    logout,
    initiateLogin,
    finalizelogin,
    getSkillPlans,
    getSkillPlan,
    createSkillPlan,
    copySkillPlan,
    deleteSkillPlan,
    saveSkillPlan,
    chooseDefaultDirectory,
    chooseSettingsDir,
    backupDirectory,
    resetToDefaultDirectory,
    syncSubdirectory,
    syncAllSubdirectories,
    saveUserSelections,
    getFuzzworksStatus,
    updateFuzzworks,
};
